#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path('../../', __FILE__)
require 'test/helper'

ARGV.each do |file|
  if file == '-v' || file == '--verbose'
    $VERBOSE = true
  else
    require file
  end
end

